# Generated by Django 6.0 on 2025-12-12 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('actividades', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinos_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinos_modificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('destinos', models.ManyToManyField(related_name='paquetes', to='api.destino')),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paquetes_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paquetes_modificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Confirmada', max_length=20)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paquete')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
